# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 540)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/icon.ico"), QtGui.QIcon.Normal)
        Form.setWindowIcon(icon)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 561, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole,
                                  self.label)
        self.lineEdit_stock = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lineEdit_stock.setFont(font)
        self.lineEdit_stock.setObjectName("lineEdit_stock")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole,
                                  self.lineEdit_stock)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole,
                                  self.label_2)
        self.lineEdit_searchkey = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lineEdit_searchkey.setFont(font)
        self.lineEdit_searchkey.setObjectName("lineEdit_searchkey")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole,
                                  self.lineEdit_searchkey)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole,
                                  self.label_3)
        self.lineEdit_from_date = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lineEdit_from_date.setFont(font)
        self.lineEdit_from_date.setObjectName("lineEdit_from_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole,
                                  self.lineEdit_from_date)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole,
                                  self.label_4)

        self.lineEdit_to_date = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lineEdit_to_date.setFont(font)
        self.lineEdit_to_date.setObjectName("lineEdit_to_date")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole,
                                  self.lineEdit_to_date)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole,
                                  self.label_5)

        self.comboBox_column = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_column.setObjectName("comboBox_column")
        self.comboBox_column.addItem("")
        self.comboBox_column.addItem("")
        self.comboBox_column.addItem("")
        self.comboBox_column.addItem("")
        self.comboBox_column.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole,
                                  self.comboBox_column)

        ## label_selected
        self.lineEdit_selected = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lineEdit_selected.setFont(font)
        self.lineEdit_selected.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole,
                                  self.lineEdit_selected)

        self.pushButton_column = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_column.setObjectName("pushButton_column")

        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole,
                                  self.pushButton_column)

        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole,
                                  self.label_9)
        self.comboBox_tabname = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_tabname.setObjectName("comboBox")
        self.comboBox_tabname.addItem("")
        self.comboBox_tabname.addItem("")
        self.comboBox_tabname.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole,
                                  self.comboBox_tabname)

        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 260, 561, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(590, 10, 120, 60))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(590, 80, 120, 60))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_clean = QtWidgets.QPushButton(Form)
        self.pushButton_clean.setGeometry(QtCore.QRect(590, 150, 120, 60))
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(590, 220, 120, 40))
        self.label_7.setObjectName("label_7")
        self.lineEdit_pageNum = QtWidgets.QLineEdit(Form)
        self.lineEdit_pageNum.setGeometry(QtCore.QRect(590, 260, 120, 30))
        self.lineEdit_pageNum.setObjectName("lineEdit_pageNum")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(590, 300, 120, 40))
        self.label_8.setObjectName("label_8")
        self.lineEdit_recordNum = QtWidgets.QLineEdit(Form)
        self.lineEdit_recordNum.setGeometry(QtCore.QRect(590, 340, 120, 30))
        self.lineEdit_recordNum.setObjectName("lineEdit_RecordNum")

        self.retranslateUi(Form)
        self.pushButton_start.clicked.connect(Form.start)
        self.pushButton_stop.clicked.connect(Form.stop)
        self.pushButton_clean.clicked.connect(Form.clean)
        self.pushButton_column.clicked.connect(Form.column_select)
        # self.textBrowser.textChanged.connect(Form.textBrowser_scroll)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "GuiCninfo"))
        self.label.setText(_translate("Form", "代码/简称/拼音"))
        self.label_2.setText(_translate("Form", "标题关键字"))
        self.label_3.setText(_translate("Form", "开始日期"))
        self.label_4.setText(_translate("Form", "结束日期"))
        self.label_5.setText(_translate("Form", "分组"))
        self.comboBox_column.setItemText(0, _translate("Form", "深京沪"))
        self.comboBox_column.setItemText(1, _translate("Form", "基金"))
        self.comboBox_column.setItemText(2, _translate("Form", "债券"))
        self.comboBox_column.setItemText(3, _translate("Form", "港股"))
        self.comboBox_column.setItemText(4, _translate("Form", "三板"))
        self.lineEdit_selected.setText(_translate("Form", "全部分类"))
        self.pushButton_column.setText(_translate("Form", "分类选择"))
        self.label_9.setText(_translate("Form", "表名"))
        self.comboBox_tabname.setItemText(0, _translate("Form", "公告"))
        self.comboBox_tabname.setItemText(1, _translate("Form", "调研"))
        self.comboBox_tabname.setItemText(2, _translate("Form", "持续督导"))
        self.pushButton_start.setText(_translate("Form", "开始"))
        self.pushButton_stop.setText(_translate("Form", "停止"))
        self.pushButton_clean.setText(_translate("Form", "清空"))

        self.lineEdit_from_date.setText(_translate("Form", self.sdate()))
        self.lineEdit_to_date.setText(_translate("Form", self.edate()))
        self.lineEdit_pageNum.setText(_translate("Form", '1'))
        self.lineEdit_recordNum.setText(_translate('Form', '1'))
        self.label_7.setText(_translate("Form", "起始页号"))
        self.label_8.setText(_translate("Form", "起始记录号"))

    @staticmethod
    def edate():
        return datetime.datetime.now().strftime("%Y-%m-%d")

    @staticmethod
    def sdate():
        return (datetime.datetime.now() - datetime.timedelta(
            weeks=1)).strftime("%Y-%m-%d")
